## Assignment - 8
In PyQuil, implement the Deutsch-Jozsa algorithm and the Bernstein-Vazirani algorithm.  Write detailed comments in the code about why it works.  Run the programs on the simulator.  Write a report that covers the following three points.

1. Design

    * Present the design of how you implemented the black-box function U_f.  Assess how visually neat and easy to read it is.
    * Present the design for how you prevent the user of U_f from accessing the implementation of U_f.  Assess how well you succeeded.
    * Present the design of how you parameterized the solution in n.
    * Discuss the number of lines and percentage of code that your two programs share.  Assess how well you succeeded in reusing code from one program to the next.


2. Evaluation

    * Discuss your effort to test the two programs and present results from the testing.  Discuss whether different cases of U_f lead to different execution times.
    * What is your experience with scalability as n grows?  Present a diagram that maps n to execution time.

3. Instructions

    * Present a README file that describes how to input the function f, how to run the program, and how to understand the output.
    * Submit three files, one for each program and one with the report.

In [33]:
import numpy as np

#sample balanced function designed for N =2 for testing the code
def f(x):
	# print(x, type(x))
	if(x =="01" or x=="10"):
		return 1
	else:
		return 0
    
#sample constant function designed for N =2 for testing the code
def f_1(x):
	return 1

#sample constant function designed for N =2 for testing the code
def f_2(x):
	return 0


#this function creates the blackbox oracle Uf matrix for a given function f that is parameterised for input size n
def createUf(f,n):
    
    #this dictionary represents the correspondence between bit combinations and Uf indices
	indices_dict = {}
	counter = 0
	Uf = np.zeros((2**(n+1),2**(n+1)))

	bfx = 0

    # the for loops given below form the different pattern combinations that we need. The mapping between these combination and Uf matrix indices is stored in indices_dict
	for i in range(2**(n+1)):
		binary_form = ('{0:0'+str(n+1)+'b}').format(i) 
		indices_dict[binary_form] = counter
		counter += 1


    #we then iterate through this pattern dictionary
	for key,val in indices_dict.items():
        
        #input to the function is the first n bits of the elements (bit patterns) from the dictionary
		x = key[0:n]
        
        #fx represents the output of function f given the input x
		fx = str(f(x))
        
        #b is the last bit of the bit pattern in the dictionary item
		b = key[n]
        
        #below we have the (f(x) + b) mod 2
		if(b==fx):
			bfx = '0'
		else:
			bfx = '1'
			# print(bfx)
        
        #the final bit string is the concatenation of the input x and bfx
		target = x + bfx
		# print('t',target)
        
        #using indices_dict we can now find the index that corresponds to this output
		target_index = indices_dict[target]
		# print(val,target_index)
        
        #now using the target indiex we can create a bit pattern with all 0s and 1 at the target index position
		Uf[val][target_index] = 1
	return Uf



# Uf = createUf(f,2)
# print(Uf)

In [34]:
def getBitVector(bitString):
    bitDict = {}
    bitDict['0'] = np.array([1 , 0])
    bitDict['1'] = np.array([0 , 1])
    matrix = [1]
    
    for c in bitString:
        matrix = np.kron(matrix,bitDict[c])
    return matrix

def getAllPossibleNBitStrings(n):
    if n==1:
        return ['0','1']
    
    children = getAllPossibleNBitStrings(n-1)
    result = []
    for i in children:
        result.append('0'+i)
        result.append('1'+i)
    return result

def getFunctionResult(function,x,ancilla):
    fx = function(x)
    newAncilla = str((((int)(ancilla) + fx)%2))
    result = x+newAncilla
    print("\tFunction Input:{} Output:{}".format(x+ancilla,result))
    return getBitVector(result)

def verifyUf(function,n):
    UfMatrix = createUf(function, n)   
    print("\nUfMatrix for function \n"+str(UfMatrix)+"\n")
    inputs = getAllPossibleNBitStrings(n+1)
    valid = True
    
    for i in inputs:
        inputBitVector = getBitVector(i)
        print("Input BitString {}".format(i))
        print("Input BitVector {}\n".format(inputBitVector))
        
        functionOutput = getFunctionResult(function,i[0:n],i[n])
        UfOutput = np.matmul(UfMatrix,inputBitVector)
        print("\tUf Output {}".format(UfOutput))
        print("\t F Output {}\n".format(functionOutput))
        
        if np.array_equal(UfOutput,functionOutput) is not True:
            print("ERROR FOR {}\n".format(i))
            valid=False
            
    return valid


print("\nVerifying F1 constant\n")
result = verifyUf(f_1,2)
print("\nF_1 constant verification result {}\n".format(result))
print("\nVerifying F2 constant\n")
result = verifyUf(f_2,2)
print("\nF_2 constant verification result {}\n".format(result))

print("\nVerifying F balanced\n")
result = verifyUf(f,2)
print("\nF balanced verification result {}\n".format(result))


Verifying F1 constant


UfMatrix for function 
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]

Input BitString 000
Input BitVector [1 0 0 0 0 0 0 0]

	Function Input:000 Output:001
	Uf Output [0. 1. 0. 0. 0. 0. 0. 0.]
	 F Output [0 1 0 0 0 0 0 0]

Input BitString 100
Input BitVector [0 0 0 0 1 0 0 0]

	Function Input:100 Output:101
	Uf Output [0. 0. 0. 0. 0. 1. 0. 0.]
	 F Output [0 0 0 0 0 1 0 0]

Input BitString 010
Input BitVector [0 0 1 0 0 0 0 0]

	Function Input:010 Output:011
	Uf Output [0. 0. 0. 1. 0. 0. 0. 0.]
	 F Output [0 0 0 1 0 0 0 0]

Input BitString 110
Input BitVector [0 0 0 0 0 0 1 0]

	Function Input:110 Output:111
	Uf Output [0. 0. 0. 0. 0. 0. 0. 1.]
	 F Output [0 0 0 0 0 0 0 1]

Input BitString 001
Input BitVector [0 1 0 0 0 0 0 0]

	Function Input:001 Output:000
	Uf Output [1. 0. 0. 0. 0. 0. 0. 0.]

In [18]:
getBitVector("000")

array([1, 0, 0, 0, 0, 0, 0, 0])

In [19]:
from pyquil import Program
from pyquil.gates import *
from pyquil import get_qc
from pyquil.quilatom import unpack_qubit
from pyquil.quil import DefGate

    
    
def runMainCircuit(function,n,nTrials):
    p = Program()
    
    UfMatrix = createUf(function,n)
    GateName = "UF_GATE"
    n = n+1
    qc_name = "{}q-qvm".format(n)
    # Get our QuantumComputer instance, with a Quantum Virutal Machine (QVM) backend
    qc = get_qc(qc_name)

    #setting last qubit to 1
    p += X(n-1)
    
    #adding Hadamard gates to all qubits
    for i in range(0,n):
        p += H(i)


    

    uf_gate_definition = DefGate(GateName, UfMatrix)
    qubits = [unpack_qubit(i) for i in range(0,n)]

    #adding Uf gate
    p+=Program(uf_gate_definition,Gate(name=GateName, params=[],qubits=qubits))

    for i in range(0,n-1):
        p += H(i)

    print(p)
        
    results = qc.run_and_measure(p, trials=nTrials)
    return results

In [20]:
# runMainCircuit(f,2)
# runMainCircuit(f_1,2)

### Deutsch-Jozsa

In [21]:
nTrials = 1

def isBalancedOrConstant(function,nQubits):
    results = runMainCircuit(function,nQubits,nTrials)
    constant = True
    for i in range(0,nQubits):
        if results[i][0] != 0:
            constant = False
            break
    
    if constant:
        return "CONSTANT"
    else:
        return "BALANCED"

In [15]:
print(isBalancedOrConstant(f,2))
print(isBalancedOrConstant(f_1,2))
print(isBalancedOrConstant(f_2,2))

DEFGATE UF_GATE:
    1.0, 0, 0, 0, 0, 0, 0, 0
    0, 1.0, 0, 0, 0, 0, 0, 0
    0, 0, 0, 1.0, 0, 0, 0, 0
    0, 0, 1.0, 0, 0, 0, 0, 0
    0, 0, 0, 0, 0, 1.0, 0, 0
    0, 0, 0, 0, 1.0, 0, 0, 0
    0, 0, 0, 0, 0, 0, 1.0, 0
    0, 0, 0, 0, 0, 0, 0, 1.0

X 2
H 0
H 1
H 2
UF_GATE 0 1 2
H 0
H 1



TimeoutError: Timeout on client tcp://127.0.0.1:5555, method name quil_to_native_quil, class info: <rpcq._client.Client object at 0x000001E60EC1FCF8>

### Bernstein-Vazirani

In [ ]:
def constructFunction(function,nQubits):
    b = function("0"*nQubits)
    a = ""
    for i in range(0,nQubits):
        a+=str(results[i][0])
    return a,b