# Headers

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import time
import itertools as itert
from pyquil import Program
import pyquil.api as api
from pyquil.quil import DefGate
from pyquil.gates import *
from pyquil import get_qc
from pyquil.quilatom import unpack_qubit

# Input possibilities

In [2]:
def get_possibilities (n):
    # whole- entire set of possible n input values. Totally there are 2**n values.
    whole=[]
    # this will ensure that all binary values obtained have same length
    max_binary_length= len(bin(2**n-1)[2:])
    # creating binary values 
    for i in range(0, 2**n):
        # this will represent actual binary value to be obtained
        curr_binary=[0]*max_binary_length
        # This gives current length of binary. Why is this required?
        # SO bin(0) return 0b0 and bin(8) returns 0b1000-> different lengths. 
        # But we want all our binary values to have same length for simplicity 
        corresponding_binary= list(bin(i))[2:] # bin returns string, we are turning it into character array/list
        # [2:] disregards the initial 0b in 0bx (returned by bin) and considers x which is the binary value  
        curr_length= len(corresponding_binary)
        for j in range(0, curr_length):
            corresponding_binary[j]=int(corresponding_binary[j]) # converting character array to int array
        # final binary value obtained
        curr_binary[max_binary_length-curr_length:]= corresponding_binary
        # adding this value as a possibility
        whole.append(curr_binary)
    print("Input Possibilities: ", whole)
    return whole

# Z_0 for G

In [3]:
def createz0 (n):
    matrix_z= np.eye(2**(n))
    matrix_z[0][0]=-1
    for i in range (0,2**n):
        matrix_z[i][i] *= (-1)
    print (" Minus Matrix Z0:")
    print(matrix_z)
    return matrix_z

# Create Uf

In [4]:
class Uf:  
    
    def __function_generator(self,n):
        # a- binary string of length n
        curr_index= np.random.randint(low=0,high=n,size=1)[0]
        a=[0]*n
        a[curr_index]=1
        #a = np.random.randint(low=0, high=2, size=n)
        print ("This is the (randomly chosen) value of a: ", a)
        # b- single bit binary digit
        #b = np.random.randint(low=0, high=2, size=1)
        #print ("This is the (randomly chosen) value of b: ", b)
        #return a,b
        return a
    
    def __unique_generator(self,n):
        # a- binary string of length n
        curr_a= np.random.randint(low=0,high=2,size=n)
        print ("This is the (randomly chosen) value of a: ", curr_a)
        return curr_a

    #this function creates the blackbox oracle Uf matrix for a given function f that is parameterised for input size n
    def __blackboxUf(self,n,a):
        uf_matrix = np.eye(2**n)
        all_binary= get_possibilities (n)
        '''for i in range(0,2**n):
            curr_dot_product=0
            for k in range (0,n):
                curr_dot_product += a[k] * int(all_binary[i][k])
            curr_dot_product %= 2
            if curr_dot_product == 1 :
                uf_matrix[i][i] *= (-1)'''
        for i in all_binary:
            if (np.array_equal(a,i)):
                uf_matrix[i][i] *= (-1)  
        print ("UF\n", uf_matrix)
        return uf_matrix
    def createUf(self,n):
        #curr_a= self.__function_generator(n)
        curr_a= self.__unique_generator(n)
        return self.__blackboxUf(n,curr_a)

# Main Circuit

In [5]:
def runMainCircuit():
   
    # Taking the input n from the user
    n= int(input("Enter length of function input [Don't include helper bit in n and ONLY Integer Values Allowed]: "))
    
    # one extra bit as our helper bit 
    #n = n+1
    
    #Number of Iterations
    num_of_iterations = max(1, int((np.pi/4)*np.sqrt(2**n)-1/2))
    
    print("Number of iterations: ", num_of_iterations)

    # creating an instance of Uf
    uf = Uf()
    
    # defining start of PyQuil program
    p = Program()
    
    qc_name = "{}q-qvm".format(n)
    
    # Get our QuantumComputer instance, with a Quantum Virutal Machine (QVM) backend
    
    qc = get_qc(qc_name)
    qc.compiler.client.timeout = 600 # number of seconds/ Increasing time out 
    
    # Time taken by program needs to be checked.
    start = time. time()
    
    
    
    # creating our Uf matrix 
   
    UfMatrix = uf.createUf(n)
    GateName = "UF_GATE_GROVER"
    
    #Zero Matrix
    matrix_z0= createz0(n)
    Gate0="minus_Z0"
    
    #defining a gate using its name and matrix
    
    uf_gate_definition = DefGate(GateName, UfMatrix)
    qubits = [unpack_qubit(i) for i in range(0,n)]
    
    z0_gate = DefGate(Gate0,matrix_z0)
    
    # adding Hadamard gates to all qubits
    for i in range(0,n):
        p += H(i)
    # adding Uf gate
    for k in range(0,num_of_iterations):
        print("Iteration no: ", k)
        p+=Program(uf_gate_definition,Gate(name=GateName, params=[],qubits=qubits))
        for i in range(0,n):
                p += H(i)
        p+=Program(z0_gate,Gate(name=Gate0, params=[],qubits=qubits))
        for i in range(0,n):
                p += H(i)
        print("Program uptil now: ", p) 
      
    
    
    # measurement result    
    results = qc.run_and_measure(p, trials=5)
    
    print("Results: ")
    print(results)
    '''
    qvm = api.QVMConnection()
    wavefunc = qvm.wavefunction(p)
    outcome_probs = wavefunc.get_outcome_probs()
    print("yyy", outcome_probs)
    print ("The most probable outcome is: |%s>" % (max(outcome_probs, key=outcome_probs.get)))
    # histogram of outcome probs
    plt.figure(figsize=(8, 6))
    plt.bar(outcome_probs.keys(), outcome_probs.values())
    plt.show()'''
    end = time. time()
    print("Time taken by program: ", end-start)

In [6]:
runMainCircuit()

Enter length of function input [Don't include helper bit in n and ONLY Integer Values Allowed]: 2
Number of iterations:  1
This is the (randomly chosen) value of a:  [0 1]
Input Possibilities:  [[0, 0], [0, 1], [1, 0], [1, 1]]
UF
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 Minus Matrix Z0:
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]
Iteration no:  0
Program uptil now:  DEFGATE UF_GATE_GROVER:
    1.0, 0, 0, 0
    0, 1.0, 0, 0
    0, 0, 1.0, 0
    0, 0, 0, 1.0

DEFGATE minus_Z0:
    1.0, 0, 0, 0
    0, -1.0, 0, 0
    0, 0, -1.0, 0
    0, 0, 0, -1.0

H 0
H 1
UF_GATE_GROVER 0 1
H 0
H 1
minus_Z0 0 1
H 0
H 1

Results: 
{0: array([0, 1, 1, 0, 1]), 1: array([0, 1, 0, 0, 1])}
Time taken by program:  0.3834826946258545


In [7]:
runMainCircuit()

Enter length of function input [Don't include helper bit in n and ONLY Integer Values Allowed]: 3
Number of iterations:  1
This is the (randomly chosen) value of a:  [1 0 1]
Input Possibilities:  [[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]]
UF
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
 Minus Matrix Z0:
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]]
Iteration no:  0
Program uptil now:  DEFGATE UF_GATE_GROVER:
    1.0, 0, 0, 0, 0, 0, 0, 0
    0, 1.0, 0, 0, 0, 0, 0, 0
    0, 0, 1.0, 0, 0, 0, 0, 0
    0, 0, 0, 1.0, 0, 0, 0, 0
    0, 0, 0, 0, 1.

In [8]:
runMainCircuit()

Enter length of function input [Don't include helper bit in n and ONLY Integer Values Allowed]: 4
Number of iterations:  2
This is the (randomly chosen) value of a:  [1 1 1 1]
Input Possibilities:  [[0, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0, 0, 1, 1], [0, 1, 0, 0], [0, 1, 0, 1], [0, 1, 1, 0], [0, 1, 1, 1], [1, 0, 0, 0], [1, 0, 0, 1], [1, 0, 1, 0], [1, 0, 1, 1], [1, 1, 0, 0], [1, 1, 0, 1], [1, 1, 1, 0], [1, 1, 1, 1]]
UF
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0

C:\Users\lenovo\Anaconda3\lib\site-packages\pyquil\quil.py:183: UserWarning: Gate UF_GATE_GROVER has already been defined in this program
  .format(instruction.name))
C:\Users\lenovo\Anaconda3\lib\site-packages\pyquil\quil.py:183: UserWarning: Gate minus_Z0 has already been defined in this program
  .format(instruction.name))


Results: 
{0: array([0, 1, 1, 0, 0]), 1: array([0, 1, 1, 0, 1]), 2: array([0, 0, 1, 0, 1]), 3: array([0, 1, 0, 0, 1])}
Time taken by program:  5.818016767501831
